Repository AY2122S1-CS2113T-F12-2/tp, pull requests merged in 2021-10, with the labels that each got.

#75 Add logging to parser.
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.Medium

#77 Add more JUnit tests for parser.
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/GeneratorTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Task, priority.High

#90 Refactor Parser class
  src/main/java/seedu/duke/GetJackd.java
  src/main/java/seedu/duke/parser/AddExerciseParser.java
  src/main/java/seedu/duke/parser/CommandManager.java
  src/main/java/seedu/duke/parser/CreateWorkoutParser.java
  src/main/java/seedu/duke/parser/DeleteWorkoutParser.java
  src/main/java/seedu/duke/parser/DisplayExerciseParser.java
  src/main/java/seedu/duke/parser/Generator.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/MarkExerciseAsDoneParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/RemoveExerciseParser.java
  src/test/java/seedu/duke/parser/CommandManagerTest.java
Labels: type.Task, priority.Medium

#97 Minimise flags
  src/main/java/seedu/duke/command/exercise/AddExerciseCommand.java
  src/main/java/seedu/duke/command/exercise/DisplayExercisesCommand.java
  src/main/java/seedu/duke/command/exercise/MarkExerciseAsDoneCommand.java
  src/main/java/seedu/duke/command/exercise/RemoveExerciseCommand.java
  src/main/java/seedu/duke/command/workout/CreateWorkoutCommand.java
  src/main/java/seedu/duke/command/workout/DeleteWorkoutCommand.java
  src/main/java/seedu/duke/parser/AddExerciseParser.java
  src/main/java/seedu/duke/parser/CreateWorkoutParser.java
  src/main/java/seedu/duke/parser/DeleteWorkoutParser.java
  src/main/java/seedu/duke/parser/DisplayExerciseParser.java
  src/main/java/seedu/duke/parser/MarkExerciseAsDoneParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/RemoveExerciseParser.java
  src/test/java/seedu/duke/parser/CommandManagerTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.Medium

#102 Add Search function.
  src/main/java/seedu/duke/command/SearchCommand.java
  src/main/java/seedu/duke/command/exercise/AddExerciseCommand.java
  src/main/java/seedu/duke/command/exercise/DisplayExercisesCommand.java
  src/main/java/seedu/duke/command/exercise/MarkExerciseAsDoneCommand.java
  src/main/java/seedu/duke/command/exercise/RemoveExerciseCommand.java
  src/main/java/seedu/duke/command/workout/CreateWorkoutCommand.java
  src/main/java/seedu/duke/command/workout/DeleteWorkoutCommand.java
  src/main/java/seedu/duke/command/workout/ListWorkoutsCommand.java
  src/main/java/seedu/duke/parser/CommandManager.java
  src/main/java/seedu/duke/parser/SearchParser.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#111 Remove WORKOUT_KEYWORD in MESSAGE_USAGE of DeleteWorkoutCommand
  build.gradle
  docs/umldg/UI.puml
  src/main/java/seedu/duke/command/exercise/DisplayExercisesCommand.java
  src/main/java/seedu/duke/command/workout/DeleteWorkoutCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#118 Add User Guide info for Commands
  docs/UserGuide.md
Labels: type.Task, priority.High
